FROM ubuntu:18.04
RUN apt update && apt install -y nodejs npm 

RUN apt-get install -y libboost-all-dev

WORKDIR /usr/src/app

RUN echo "Here"

COPY . .
RUN npm install
RUN chmod 777 /usr/src/app

EXPOSE 8088
EXPOSE 9878

CMD node /usr/src/app/src/main.js