FROM ubuntu:18.04
RUN apt update && apt install -y nodejs npm 

RUN apt-get install -y libboost-all-dev
RUN apt-get update && apt-get install -y git

WORKDIR /usr/src/app

COPY . .
RUN chmod 777 /usr/src/app

EXPOSE 8088
EXPOSE 9878

CMD node /usr/src/app/src/main.js