version: 2
jobs:
  build:
    docker:
      # Primary
      - image: node:12.18.3-buster
        environment:
          rabbitmq__url: amqp://guest:guest@127.0.0.1:5672/
      - image: redis:3.2.3
      - image: rabbitmq:3.6.4-management
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Installing pre-requisite dependencies
          command: apt-get -qq update && apt-get install libc6-dev && apt-get -qq install -y libboost-all-dev libsodium-dev libsodium23 netcat
      - run:
          name: Waiting for cache to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 6379 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Cache && exit 1
      - run:
          name: Installing cryptoforknote library
          command: |
            npm install https://github.com/myriadeinc/cryptonote-lib.git 
      - run:
          name: Installing dev dependencies
          command: |
            npm install
      - run:
          name: Run Tests
          command: |
            npm run test
      - run:
          name: Installing Docker to build image
          command: |
            apt-get -qq install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common && \
            curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add && \
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
            apt-get -qq update && apt-get install -y docker-ce
      - run:
          name: Build Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            TAG=$(git show -s --pretty=%H) make build
      - deploy:
          name: Push & deploy build
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push myriadeinc/emerald:$(git show -s --pretty=%H)
            fi