steps:
  - command: "npm install"
    label: "Installing"

  - wait

  - command: "npm run test"
    label: "Running Tests"

  - wait

  - commands:
      - "docker build . -t myriade/emerald:"
      - "docker push myriade/emerald:latest"
    plugins:
      - docker#v3.3.0:
          image: "docker:latest"
          always-pull: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"